import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'error_text': 'Something went wrong!',
          'unknown_error': 'Unknown error! Try again or contact support.',
          'hello': 'Hello Flutter!',
          'store': 'Store.com',
          'settings': 'Settings',
          'settings_theme': 'Theme',
          'settings_lang': 'English',
          'shopping_cart': 'Shopping Cart',
          'shopping_cart_button': 'Add to Shopping Cart',
          'sign_in': 'Sign In',
          'currency': 'USD',
          'purchasedCount': 'Purchased Count',
          'empty_cart': 'Empty Cart',
          'password_repeat': 'Repeat your password',
          'sign_in_titel': 'Sign In',
          'sign_in_email': 'Enter your email',
          'sign_in_password': 'Enter your password',
          'sign_in_password_error': 'More than 6 characters',
          'sign_in_password_equil_error': 'Passwords do not match',
          'sign_in_email_error': 'Enter correct email',
          'sign_in_email_in_use': 'Email already in use',
          'wrong_password_or_email': 'Wrong email or password. Try again.',
          'warning_text': 'Warning!',
          'sign_up_titel': 'Sign Up',
          'button_buy': 'Buy',
          'items_count_titel': 'items',
          'user_error': 'You need to sign in to buy a product.',
          'product_buy_success': 'Thank you for your order',
          'receipt': 'Receipt',
          'notification': 'Notification',
          'home_titel': 'Home',
          'sign_in_google': 'Sign in with Google',
          'or': 'or with',
        },
        'uk_UA': {
          'error_text': 'Щось пішло не так!',
          'unknown_error':
              'Невідома помилка! Повторіть спробу або зверніться в підтримку.',
          'hello': 'Привіт Флаттер!',
          'store': 'Mаркет.ua',
          'settings': 'Налаштування',
          'settings_theme': 'Тема',
          'settings_lang': 'Українська',
          'shopping_cart': 'Кошик',
          'shopping_cart_button': 'Додати в кошик',
          'sign_in': 'Увійти',
          'currency': 'грн',
          'purchasedCount': 'Куплено',
          'empty_cart': 'Пустий кошик',
          'password_repeat': 'Повторіть ваш пароль',
          'sign_in_titel': 'Увійти',
          'sign_in_email': 'Введіть ваш email',
          'sign_in_password': 'Введіть ваш пароль',
          'sign_in_password_error': 'Більше 6 символів',
          'sign_in_password_equil_error': 'Паролі не співпадають',
          'sign_in_email_error': 'Введіть коректний email',
          'sign_in_email_in_use': 'Email вже використовується',
          'wrong_password_or_email':
              'Неправильний email або пароль. Спробуйте ще раз.',
          'warning_text': 'Увага!',
          'sign_up_titel': 'Зареєструватися',
          'button_buy': 'Купити',
          'items_count_titel': 'од. товару',
          'user_error': 'Необхідно увійти в систему для покупки товару.',
          'product_buy_success': 'Дякуємо за ваше замовлення',
          'receipt': 'Чек',
          'notification': 'Повідомлення',
          'home_titel': 'Головна',
          'sign_in_google': 'Увійти через Google',
          'or': 'або через',
        },
      };
}
